In [15]:
from colorspacious import cspace_convert
import matplotlib as mpl

In [16]:
cspace_convert([128, 128, 128], "sRGB255", "CIELab")

array([ 5.35840168e+01,  4.47118403e-03, -7.16147720e-03])

In [17]:
splits = 1000
colour_values = mpl.cm.Reds(np.linspace(0, 1, splits))

In [18]:
colour_values_rgb = colour_values[:, :3]
colour_values_rgb


array([[1.        , 0.96078431, 0.94117647],
       [1.        , 0.96078431, 0.94117647],
       [1.        , 0.96078431, 0.94117647],
       ...,
       [0.40392157, 0.        , 0.05098039],
       [0.40392157, 0.        , 0.05098039],
       [0.40392157, 0.        , 0.05098039]])

In [20]:
cspace_convert(colour_values_rgb, "sRGB1", "CIELab")

array([[97.16752233,  2.50184937,  3.58068877],
       [97.16752233,  2.50184937,  3.58068877],
       [97.16752233,  2.50184937,  3.58068877],
       ...,
       [19.68974764, 41.48725414, 24.73234583],
       [19.68974764, 41.48725414, 24.73234583],
       [19.68974764, 41.48725414, 24.73234583]])